# ** Do not edit this file. Regenerate it using `make sync-test-data` **

package lib.tekton_test

import rego.v1

att_01_slsa_v0_2_pipeline_in_cluster := {
	"_type": "https://in-toto.io/Statement/v0.1",
	"predicateType": "https://slsa.dev/provenance/v0.2",
	"subject": [{
		"name": "quay.io/lucarval/test-policies-chains",
		"digest": {"sha256": "2cfcb34dcaabc76e331dc9b28c3256a3d0508f6ddf6b3a9fee156c9bfce91c85"},
	}],
	"predicate": {
		"builder": {"id": "https://tekton.dev/chains/v2"},
		"buildType": "tekton.dev/v1beta1/PipelineRun",
		"invocation": {
			"configSource": {},
			"parameters": {
				"IMAGE_DIGEST": "sha256:2cfcb34dcaabc76e331dc9b28c3256a3d0508f6ddf6b3a9fee156c9bfce91c85",
				"IMAGE_URL": "quay.io/lucarval/test-policies-chains",
				"TEST_OUTPUT": "missing",
				"commit": "a95a628c6bb3de64fe3a56aea3d367a7fd1628a6",
				"committer-date": "1704741370",
				"url": "gitspam.spam/spam/spam",
			},
			"environment": {"labels": {"tekton.dev/pipeline": "simple-build"}},
		},
		"buildConfig": {"tasks": [
			{
				"name": "git-clone",
				"ref": {
					"kind": "Task",
					"resolver": "git",
					"params": [
						{
							"name": "url",
							"value": "https://github.com/conforma/hacks.git",
						},
						{
							"name": "revision",
							"value": "4fceb2416020011e794105f113a3913ef659c8ee",
						},
						{
							"name": "pathInRepo",
							"value": "provenance/task/mock-git-clone.yaml",
						},
					],
				},
				"startedOn": "2024-01-08T19:16:11Z",
				"finishedOn": "2024-01-08T19:16:15Z",
				"status": "Succeeded",
				"steps": [{
					"entryPoint": "#!/usr/bin/env sh\nset -euo pipefail\n\necho -n \"${COMMIT}\" > \"/tekton/results/commit\"\necho -n \"${URL}\" > \"/tekton/results/url\"\necho -n \"${COMMITTER_DATE}\" > \"/tekton/results/committer-date\"\n",
					"arguments": null,
					"environment": {
						"container": "clone",
						"image": "oci://registry.access.redhat.com/ubi9@sha256:fc300be6adbdf2ca812ad01efd0dee2a3e3f5d33958ad6cd99159e25e9ee1398",
					},
					"annotations": null,
				}],
				"invocation": {
					"configSource": {
						"uri": "git+https://github.com/conforma/hacks.git",
						"digest": {"sha1": "4fceb2416020011e794105f113a3913ef659c8ee"},
						"entryPoint": "provenance/task/mock-git-clone.yaml",
					},
					"parameters": {
						"commit": "a95a628c6bb3de64fe3a56aea3d367a7fd1628a6",
						"committer-date": "1704741370",
						"url": "gitspam.spam/spam/spam",
					},
					"environment": {
						"annotations": {"pipeline.tekton.dev/release": "e59ee42"},
						"labels": {
							"app.kubernetes.io/managed-by": "tekton-pipelines",
							"tekton.dev/memberOf": "tasks",
							"tekton.dev/pipeline": "simple-build",
							"tekton.dev/pipelineRun": "simple-build-run-a2595b597b",
							"tekton.dev/pipelineTask": "git-clone",
							"tekton.dev/task": "mock-git-clone",
						},
					},
				},
				"results": [
					{
						"name": "commit",
						"type": "string",
						"value": "a95a628c6bb3de64fe3a56aea3d367a7fd1628a6",
					},
					{
						"name": "committer-date",
						"type": "string",
						"value": "1704741370",
					},
					{
						"name": "url",
						"type": "string",
						"value": "gitspam.spam/spam/spam",
					},
				],
			},
			{
				"name": "scan",
				"after": ["git-clone"],
				"ref": {},
				"startedOn": "2024-01-08T19:16:15Z",
				"finishedOn": "2024-01-08T19:16:19Z",
				"status": "Succeeded",
				"steps": [{
					"entryPoint": "#!/usr/bin/env sh\nset -euo pipefail\n\necho -n \"${TEST_OUTPUT}\" > \"/tekton/results/TEST_OUTPUT\"\n",
					"arguments": null,
					"environment": {
						"container": "scan",
						"image": "oci://registry.access.redhat.com/ubi9@sha256:fc300be6adbdf2ca812ad01efd0dee2a3e3f5d33958ad6cd99159e25e9ee1398",
					},
					"annotations": null,
				}],
				"invocation": {
					"configSource": {},
					"parameters": {"TEST_OUTPUT": "missing"},
					"environment": {
						"annotations": {"pipeline.tekton.dev/release": "e59ee42"},
						"labels": {
							"app.kubernetes.io/managed-by": "tekton-pipelines",
							"tekton.dev/memberOf": "tasks",
							"tekton.dev/pipeline": "simple-build",
							"tekton.dev/pipelineRun": "simple-build-run-a2595b597b",
							"tekton.dev/pipelineTask": "scan",
						},
					},
				},
				"results": [{
					"name": "TEST_OUTPUT",
					"type": "string",
					"value": "missing",
				}],
			},
			{
				"name": "av-scan",
				"after": ["git-clone"],
				"ref": {
					"name": "mock-av-scanner",
					"kind": "Task",
				},
				"startedOn": "2024-01-08T19:16:15Z",
				"finishedOn": "2024-01-08T19:16:19Z",
				"status": "Succeeded",
				"steps": [{
					"entryPoint": "#!/usr/bin/env sh\nset -euo pipefail\n\necho -n \"${TEST_OUTPUT}\" > \"/tekton/results/TEST_OUTPUT\"\n",
					"arguments": null,
					"environment": {
						"container": "scan",
						"image": "oci://registry.access.redhat.com/ubi9@sha256:fc300be6adbdf2ca812ad01efd0dee2a3e3f5d33958ad6cd99159e25e9ee1398",
					},
					"annotations": null,
				}],
				"invocation": {
					"configSource": {},
					"parameters": {"TEST_OUTPUT": "missing"},
					"environment": {
						"annotations": {"pipeline.tekton.dev/release": "e59ee42"},
						"labels": {
							"app.kubernetes.io/managed-by": "tekton-pipelines",
							"tekton.dev/memberOf": "tasks",
							"tekton.dev/pipeline": "simple-build",
							"tekton.dev/pipelineRun": "simple-build-run-a2595b597b",
							"tekton.dev/pipelineTask": "av-scan",
							"tekton.dev/task": "mock-av-scanner",
						},
					},
				},
				"results": [{
					"name": "TEST_OUTPUT",
					"type": "string",
					"value": "missing",
				}],
			},
			{
				"name": "build",
				"after": ["scan"],
				"ref": {
					"kind": "Task",
					"resolver": "bundles",
					"params": [
						{
							"name": "bundle",
							"value": "quay.io/lucarval/test-policies-chains@sha256:ae5952d5aac1664fbeae9191d9445244051792af903d28d3e0084e9d9b7cce61",
						},
						{
							"name": "name",
							"value": "mock-build",
						},
						{
							"name": "kind",
							"value": "task",
						},
					],
				},
				"startedOn": "2024-01-08T19:16:19Z",
				"finishedOn": "2024-01-08T19:16:23Z",
				"status": "Succeeded",
				"steps": [{
					"entryPoint": "#!/usr/bin/env sh\nset -euo pipefail\n\necho -n \"${IMAGE_URL}\" > \"/tekton/results/IMAGE_URL\"\necho -n \"${IMAGE_DIGEST}\" > \"/tekton/results/IMAGE_DIGEST\"\n",
					"arguments": null,
					"environment": {
						"container": "build-and-push",
						"image": "oci://registry.access.redhat.com/ubi9@sha256:fc300be6adbdf2ca812ad01efd0dee2a3e3f5d33958ad6cd99159e25e9ee1398",
					},
					"annotations": null,
				}],
				"invocation": {
					"configSource": {
						"uri": "quay.io/lucarval/test-policies-chains",
						"digest": {"sha256": "ae5952d5aac1664fbeae9191d9445244051792af903d28d3e0084e9d9b7cce61"},
						"entryPoint": "mock-build",
					},
					"parameters": {
						"IMAGE_DIGEST": "sha256:2cfcb34dcaabc76e331dc9b28c3256a3d0508f6ddf6b3a9fee156c9bfce91c85",
						"IMAGE_URL": "quay.io/lucarval/test-policies-chains",
					},
					"environment": {
						"annotations": {"pipeline.tekton.dev/release": "e59ee42"},
						"labels": {
							"app.kubernetes.io/managed-by": "tekton-pipelines",
							"tekton.dev/memberOf": "tasks",
							"tekton.dev/pipeline": "simple-build",
							"tekton.dev/pipelineRun": "simple-build-run-a2595b597b",
							"tekton.dev/pipelineTask": "build",
							"tekton.dev/task": "mock-build",
						},
					},
				},
				"results": [
					{
						"name": "IMAGE_DIGEST",
						"type": "string",
						"value": "sha256:2cfcb34dcaabc76e331dc9b28c3256a3d0508f6ddf6b3a9fee156c9bfce91c85",
					},
					{
						"name": "IMAGE_URL",
						"type": "string",
						"value": "quay.io/lucarval/test-policies-chains",
					},
				],
			},
		]},
		"metadata": {
			"buildStartedOn": "2024-01-08T19:16:10Z",
			"buildFinishedOn": "2024-01-08T19:16:23Z",
			"completeness": {
				"parameters": false,
				"environment": false,
				"materials": false,
			},
			"reproducible": false,
		},
		"materials": [
			{
				"uri": "oci://registry.access.redhat.com/ubi9",
				"digest": {"sha256": "fc300be6adbdf2ca812ad01efd0dee2a3e3f5d33958ad6cd99159e25e9ee1398"},
			},
			{
				"uri": "git+https://github.com/conforma/hacks.git",
				"digest": {"sha1": "4fceb2416020011e794105f113a3913ef659c8ee"},
			},
			{
				"uri": "quay.io/lucarval/test-policies-chains",
				"digest": {"sha256": "ae5952d5aac1664fbeae9191d9445244051792af903d28d3e0084e9d9b7cce61"},
			},
			{
				"uri": "git+gitspam.spam/spam/spam.git",
				"digest": {"sha1": "a95a628c6bb3de64fe3a56aea3d367a7fd1628a6"},
			},
		],
	},
}

att_05_slsa_v1_0_tekton_build_type_pipeline_in_cluster := {
	"_type": "https://in-toto.io/Statement/v1",
	"subject": [{
		"name": "quay.io/st3penta-konflux-test-registry/user-ns2/cli",
		"digest": {"sha256": "ec9ff4559ae099b07c24c71257bd25859b0fbdd4414a12cd461ba261ba018e31"},
	}],
	"predicateType": "https://slsa.dev/provenance/v1",
	"predicate": {
		"buildDefinition": {
			"buildType": "https://tekton.dev/chains/v2/slsa",
			"externalParameters": {"runSpec": {
				"params": [
					{
						"name": "git-url",
						"value": "https://github.com/st3penta/cli",
					},
					{
						"name": "revision",
						"value": "82126ebeeb0d80883d5d85f4f48066821464e3d8",
					},
					{
						"name": "output-image",
						"value": "quay.io/st3penta-konflux-test-registry/user-ns2/cli:82126ebeeb0d80883d5d85f4f48066821464e3d8",
					},
					{
						"name": "dockerfile",
						"value": "Dockerfile",
					},
				],
				"pipelineSpec": {
					"description": "This pipeline is ideal for building container images from a Containerfile while maintaining trust after pipeline customization.\n\n_Uses `buildah` to create a container image leveraging [trusted artifacts](https://konflux-ci.dev/architecture/ADR/0036-trusted-artifacts.html). It also optionally creates a source image and runs some build-time tests. Information is shared between tasks using OCI artifacts instead of PVCs. EC will pass the [`trusted_task.trusted`](https://conforma.dev/docs/policy/packages/release_trusted_task.html#trusted_task__trusted) policy as long as all data used to build the artifact is generated from trusted tasks.\nThis pipeline is pushed as a Tekton bundle to [quay.io](https://quay.io/repository/konflux-ci/tekton-catalog/pipeline-docker-build-oci-ta?tab=tags)_\n",
					"params": [
						{
							"description": "Source Repository URL",
							"name": "git-url",
							"type": "string",
						},
						{
							"default": "",
							"description": "Revision of the Source Repository",
							"name": "revision",
							"type": "string",
						},
						{
							"description": "Fully Qualified Output Image",
							"name": "output-image",
							"type": "string",
						},
						{
							"default": ".",
							"description": "Path to the source code of an application's component from where to build image.",
							"name": "path-context",
							"type": "string",
						},
						{
							"default": "Dockerfile",
							"description": "Path to the Dockerfile inside the context specified by parameter path-context",
							"name": "dockerfile",
							"type": "string",
						},
						{
							"default": "false",
							"description": "Force rebuild image",
							"name": "rebuild",
							"type": "string",
						},
						{
							"default": "false",
							"description": "Skip checks against built image",
							"name": "skip-checks",
							"type": "string",
						},
						{
							"default": "false",
							"description": "Execute the build with network isolation",
							"name": "hermetic",
							"type": "string",
						},
						{
							"default": "",
							"description": "Build dependencies to be prefetched",
							"name": "prefetch-input",
							"type": "string",
						},
						{
							"default": "",
							"description": "Image tag expiration time, time values could be something like 1h, 2d, 3w for hours, days, and weeks, respectively.",
							"name": "image-expires-after",
							"type": "string",
						},
						{
							"default": "false",
							"description": "Build a source image.",
							"name": "build-source-image",
							"type": "string",
						},
						{
							"default": "false",
							"description": "Add built image into an OCI image index",
							"name": "build-image-index",
							"type": "string",
						},
						{
							"default": "docker",
							"description": "The format for the resulting image's mediaType. Valid values are oci or docker.",
							"name": "buildah-format",
							"type": "string",
						},
						{
							"default": [],
							"description": "Array of --build-arg values (\"arg=value\" strings) for buildah",
							"name": "build-args",
							"type": "array",
						},
						{
							"default": "",
							"description": "Path to a file with build arguments for buildah, see https://www.mankier.com/1/buildah-build#--build-arg-file",
							"name": "build-args-file",
							"type": "string",
						},
						{
							"default": "false",
							"description": "Whether to enable privileged mode, should be used only with remote VMs",
							"name": "privileged-nested",
							"type": "string",
						},
					],
					"results": [
						{
							"description": "",
							"name": "IMAGE_URL",
							"value": "$(tasks.build-image-index.results.IMAGE_URL)",
						},
						{
							"description": "",
							"name": "IMAGE_DIGEST",
							"value": "$(tasks.build-image-index.results.IMAGE_DIGEST)",
						},
						{
							"description": "",
							"name": "CHAINS-GIT_URL",
							"value": "$(tasks.clone-repository.results.url)",
						},
						{
							"description": "",
							"name": "CHAINS-GIT_COMMIT",
							"value": "$(tasks.clone-repository.results.commit)",
						},
					],
					"tasks": [
						{
							"name": "init",
							"params": [
								{
									"name": "image-url",
									"value": "$(params.output-image)",
								},
								{
									"name": "rebuild",
									"value": "$(params.rebuild)",
								},
								{
									"name": "skip-checks",
									"value": "$(params.skip-checks)",
								},
							],
							"taskRef": {
								"params": [
									{
										"name": "name",
										"value": "init",
									},
									{
										"name": "bundle",
										"value": "quay.io/konflux-ci/tekton-catalog/task-init:0.2@sha256:bbf313b09740fb39b3343bc69ee94b2a2c21d16a9304f9b7c111c305558fc346",
									},
									{
										"name": "kind",
										"value": "task",
									},
								],
								"resolver": "bundles",
							},
						},
						{
							"name": "clone-repository",
							"params": [
								{
									"name": "url",
									"value": "$(params.git-url)",
								},
								{
									"name": "revision",
									"value": "$(params.revision)",
								},
								{
									"name": "ociStorage",
									"value": "$(params.output-image).git",
								},
								{
									"name": "ociArtifactExpiresAfter",
									"value": "$(params.image-expires-after)",
								},
							],
							"runAfter": ["init"],
							"taskRef": {
								"params": [
									{
										"name": "name",
										"value": "git-clone-oci-ta",
									},
									{
										"name": "bundle",
										"value": "quay.io/konflux-ci/tekton-catalog/task-git-clone-oci-ta:0.1@sha256:f21c34e50500edc84e4889d85fd71a80d79182b16c044adc7f5ecda021c6dfc7",
									},
									{
										"name": "kind",
										"value": "task",
									},
								],
								"resolver": "bundles",
							},
							"when": [{
								"input": "$(tasks.init.results.build)",
								"operator": "in",
								"values": ["true"],
							}],
							"workspaces": [{
								"name": "basic-auth",
								"workspace": "git-auth",
							}],
						},
						{
							"name": "prefetch-dependencies",
							"params": [
								{
									"name": "input",
									"value": "$(params.prefetch-input)",
								},
								{
									"name": "SOURCE_ARTIFACT",
									"value": "$(tasks.clone-repository.results.SOURCE_ARTIFACT)",
								},
								{
									"name": "ociStorage",
									"value": "$(params.output-image).prefetch",
								},
								{
									"name": "ociArtifactExpiresAfter",
									"value": "$(params.image-expires-after)",
								},
							],
							"runAfter": ["clone-repository"],
							"taskRef": {
								"params": [
									{
										"name": "name",
										"value": "prefetch-dependencies-oci-ta",
									},
									{
										"name": "bundle",
										"value": "quay.io/konflux-ci/tekton-catalog/task-prefetch-dependencies-oci-ta:0.2@sha256:dc82a7270aace9b1c26f7e96f8ccab2752e53d32980c41a45e1733baad76cde6",
									},
									{
										"name": "kind",
										"value": "task",
									},
								],
								"resolver": "bundles",
							},
							"workspaces": [
								{
									"name": "git-basic-auth",
									"workspace": "git-auth",
								},
								{
									"name": "netrc",
									"workspace": "netrc",
								},
							],
						},
						{
							"name": "build-container",
							"params": [
								{
									"name": "IMAGE",
									"value": "$(params.output-image)",
								},
								{
									"name": "DOCKERFILE",
									"value": "$(params.dockerfile)",
								},
								{
									"name": "CONTEXT",
									"value": "$(params.path-context)",
								},
								{
									"name": "HERMETIC",
									"value": "$(params.hermetic)",
								},
								{
									"name": "PREFETCH_INPUT",
									"value": "$(params.prefetch-input)",
								},
								{
									"name": "IMAGE_EXPIRES_AFTER",
									"value": "$(params.image-expires-after)",
								},
								{
									"name": "COMMIT_SHA",
									"value": "$(tasks.clone-repository.results.commit)",
								},
								{
									"name": "BUILD_ARGS",
									"value": ["$(params.build-args[*])"],
								},
								{
									"name": "BUILD_ARGS_FILE",
									"value": "$(params.build-args-file)",
								},
								{
									"name": "PRIVILEGED_NESTED",
									"value": "$(params.privileged-nested)",
								},
								{
									"name": "SOURCE_URL",
									"value": "$(tasks.clone-repository.results.url)",
								},
								{
									"name": "BUILDAH_FORMAT",
									"value": "$(params.buildah-format)",
								},
								{
									"name": "SOURCE_ARTIFACT",
									"value": "$(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)",
								},
								{
									"name": "CACHI2_ARTIFACT",
									"value": "$(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)",
								},
							],
							"runAfter": ["prefetch-dependencies"],
							"taskRef": {
								"params": [
									{
										"name": "name",
										"value": "buildah-oci-ta",
									},
									{
										"name": "bundle",
										"value": "quay.io/konflux-ci/tekton-catalog/task-buildah-oci-ta:0.5@sha256:38d08ea58511a67f8754dc025feebdec8ae342fb4e25bc67a3726ec84f7cb7d1",
									},
									{
										"name": "kind",
										"value": "task",
									},
								],
								"resolver": "bundles",
							},
							"when": [{
								"input": "$(tasks.init.results.build)",
								"operator": "in",
								"values": ["true"],
							}],
						},
						{
							"name": "build-image-index",
							"params": [
								{
									"name": "IMAGE",
									"value": "$(params.output-image)",
								},
								{
									"name": "COMMIT_SHA",
									"value": "$(tasks.clone-repository.results.commit)",
								},
								{
									"name": "IMAGE_EXPIRES_AFTER",
									"value": "$(params.image-expires-after)",
								},
								{
									"name": "ALWAYS_BUILD_INDEX",
									"value": "$(params.build-image-index)",
								},
								{
									"name": "IMAGES",
									"value": ["$(tasks.build-container.results.IMAGE_URL)@$(tasks.build-container.results.IMAGE_DIGEST)"],
								},
								{
									"name": "BUILDAH_FORMAT",
									"value": "$(params.buildah-format)",
								},
							],
							"runAfter": ["build-container"],
							"taskRef": {
								"params": [
									{
										"name": "name",
										"value": "build-image-index",
									},
									{
										"name": "bundle",
										"value": "quay.io/konflux-ci/tekton-catalog/task-build-image-index:0.1@sha256:79784d53749584bc5a8de32142ec4e2f01cdbf42c20d94e59280e0b927c8597d",
									},
									{
										"name": "kind",
										"value": "task",
									},
								],
								"resolver": "bundles",
							},
							"when": [{
								"input": "$(tasks.init.results.build)",
								"operator": "in",
								"values": ["true"],
							}],
						},
						{
							"name": "build-source-image",
							"params": [
								{
									"name": "BINARY_IMAGE",
									"value": "$(tasks.build-image-index.results.IMAGE_URL)",
								},
								{
									"name": "BINARY_IMAGE_DIGEST",
									"value": "$(tasks.build-image-index.results.IMAGE_DIGEST)",
								},
								{
									"name": "SOURCE_ARTIFACT",
									"value": "$(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)",
								},
								{
									"name": "CACHI2_ARTIFACT",
									"value": "$(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)",
								},
							],
							"runAfter": ["build-image-index"],
							"taskRef": {
								"params": [
									{
										"name": "name",
										"value": "source-build-oci-ta",
									},
									{
										"name": "bundle",
										"value": "quay.io/konflux-ci/tekton-catalog/task-source-build-oci-ta:0.3@sha256:36d44f2924f60da00a079a9ab7ce25ad8b2ad593c16d90509203c125ff0ccd46",
									},
									{
										"name": "kind",
										"value": "task",
									},
								],
								"resolver": "bundles",
							},
							"when": [
								{
									"input": "$(tasks.init.results.build)",
									"operator": "in",
									"values": ["true"],
								},
								{
									"input": "$(params.build-source-image)",
									"operator": "in",
									"values": ["true"],
								},
							],
						},
						{
							"name": "deprecated-base-image-check",
							"params": [
								{
									"name": "IMAGE_URL",
									"value": "$(tasks.build-image-index.results.IMAGE_URL)",
								},
								{
									"name": "IMAGE_DIGEST",
									"value": "$(tasks.build-image-index.results.IMAGE_DIGEST)",
								},
							],
							"runAfter": ["build-image-index"],
							"taskRef": {
								"params": [
									{
										"name": "name",
										"value": "deprecated-image-check",
									},
									{
										"name": "bundle",
										"value": "quay.io/konflux-ci/tekton-catalog/task-deprecated-image-check:0.5@sha256:1d07d16810c26713f3d875083924d93697900147364360587ccb5a63f2c31012",
									},
									{
										"name": "kind",
										"value": "task",
									},
								],
								"resolver": "bundles",
							},
							"when": [{
								"input": "$(params.skip-checks)",
								"operator": "in",
								"values": ["false"],
							}],
						},
						{
							"name": "clair-scan",
							"params": [
								{
									"name": "image-digest",
									"value": "$(tasks.build-image-index.results.IMAGE_DIGEST)",
								},
								{
									"name": "image-url",
									"value": "$(tasks.build-image-index.results.IMAGE_URL)",
								},
							],
							"runAfter": ["build-image-index"],
							"taskRef": {
								"params": [
									{
										"name": "name",
										"value": "clair-scan",
									},
									{
										"name": "bundle",
										"value": "quay.io/konflux-ci/tekton-catalog/task-clair-scan:0.3@sha256:a7cc183967f89c4ac100d04ab8f81e54733beee60a0528208107c9a22d3c43af",
									},
									{
										"name": "kind",
										"value": "task",
									},
								],
								"resolver": "bundles",
							},
							"when": [{
								"input": "$(params.skip-checks)",
								"operator": "in",
								"values": ["false"],
							}],
						},
						{
							"name": "ecosystem-cert-preflight-checks",
							"params": [{
								"name": "image-url",
								"value": "$(tasks.build-image-index.results.IMAGE_URL)",
							}],
							"runAfter": ["build-image-index"],
							"taskRef": {
								"params": [
									{
										"name": "name",
										"value": "ecosystem-cert-preflight-checks",
									},
									{
										"name": "bundle",
										"value": "quay.io/konflux-ci/tekton-catalog/task-ecosystem-cert-preflight-checks:0.2@sha256:7db70c6cf23f39b9aad8b75285df31ed2c1213d87842cd4502ffc268808c96c6",
									},
									{
										"name": "kind",
										"value": "task",
									},
								],
								"resolver": "bundles",
							},
							"when": [{
								"input": "$(params.skip-checks)",
								"operator": "in",
								"values": ["false"],
							}],
						},
						{
							"name": "sast-snyk-check",
							"params": [
								{
									"name": "image-digest",
									"value": "$(tasks.build-image-index.results.IMAGE_DIGEST)",
								},
								{
									"name": "image-url",
									"value": "$(tasks.build-image-index.results.IMAGE_URL)",
								},
								{
									"name": "SOURCE_ARTIFACT",
									"value": "$(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)",
								},
								{
									"name": "CACHI2_ARTIFACT",
									"value": "$(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)",
								},
							],
							"runAfter": ["build-image-index"],
							"taskRef": {
								"params": [
									{
										"name": "name",
										"value": "sast-snyk-check-oci-ta",
									},
									{
										"name": "bundle",
										"value": "quay.io/konflux-ci/tekton-catalog/task-sast-snyk-check-oci-ta:0.4@sha256:181d63c126e3119a9d57b8feed4eb66a875b5208c3e90724c22758e65dca8733",
									},
									{
										"name": "kind",
										"value": "task",
									},
								],
								"resolver": "bundles",
							},
							"when": [{
								"input": "$(params.skip-checks)",
								"operator": "in",
								"values": ["false"],
							}],
						},
						{
							"name": "clamav-scan",
							"params": [
								{
									"name": "image-digest",
									"value": "$(tasks.build-image-index.results.IMAGE_DIGEST)",
								},
								{
									"name": "image-url",
									"value": "$(tasks.build-image-index.results.IMAGE_URL)",
								},
							],
							"runAfter": ["build-image-index"],
							"taskRef": {
								"params": [
									{
										"name": "name",
										"value": "clamav-scan",
									},
									{
										"name": "bundle",
										"value": "quay.io/konflux-ci/tekton-catalog/task-clamav-scan:0.3@sha256:b0bd59748cda4a7abf311e4f448e6c1d00c6b6d8c0ecc1c2eb33e08dc0e0b802",
									},
									{
										"name": "kind",
										"value": "task",
									},
								],
								"resolver": "bundles",
							},
							"when": [{
								"input": "$(params.skip-checks)",
								"operator": "in",
								"values": ["false"],
							}],
						},
						{
							"name": "sast-coverity-check",
							"params": [
								{
									"name": "image-digest",
									"value": "$(tasks.build-image-index.results.IMAGE_DIGEST)",
								},
								{
									"name": "image-url",
									"value": "$(tasks.build-image-index.results.IMAGE_URL)",
								},
								{
									"name": "IMAGE",
									"value": "$(params.output-image)",
								},
								{
									"name": "DOCKERFILE",
									"value": "$(params.dockerfile)",
								},
								{
									"name": "CONTEXT",
									"value": "$(params.path-context)",
								},
								{
									"name": "HERMETIC",
									"value": "$(params.hermetic)",
								},
								{
									"name": "PREFETCH_INPUT",
									"value": "$(params.prefetch-input)",
								},
								{
									"name": "IMAGE_EXPIRES_AFTER",
									"value": "$(params.image-expires-after)",
								},
								{
									"name": "COMMIT_SHA",
									"value": "$(tasks.clone-repository.results.commit)",
								},
								{
									"name": "BUILD_ARGS",
									"value": ["$(params.build-args[*])"],
								},
								{
									"name": "BUILD_ARGS_FILE",
									"value": "$(params.build-args-file)",
								},
								{
									"name": "SOURCE_ARTIFACT",
									"value": "$(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)",
								},
								{
									"name": "CACHI2_ARTIFACT",
									"value": "$(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)",
								},
							],
							"runAfter": ["coverity-availability-check"],
							"taskRef": {
								"params": [
									{
										"name": "name",
										"value": "sast-coverity-check-oci-ta",
									},
									{
										"name": "bundle",
										"value": "quay.io/konflux-ci/tekton-catalog/task-sast-coverity-check-oci-ta:0.3@sha256:cdbe1a968676e4f5519b082bf1e27a4cdcf66dd60af66dbc26b3e604f957f7e9",
									},
									{
										"name": "kind",
										"value": "task",
									},
								],
								"resolver": "bundles",
							},
							"when": [
								{
									"input": "$(params.skip-checks)",
									"operator": "in",
									"values": ["false"],
								},
								{
									"input": "$(tasks.coverity-availability-check.results.STATUS)",
									"operator": "in",
									"values": ["success"],
								},
							],
						},
						{
							"name": "coverity-availability-check",
							"runAfter": ["build-image-index"],
							"taskRef": {
								"params": [
									{
										"name": "name",
										"value": "coverity-availability-check",
									},
									{
										"name": "bundle",
										"value": "quay.io/konflux-ci/tekton-catalog/task-coverity-availability-check:0.2@sha256:db2b267dc15e4ed17f704ee91b8e9b38068e1a35b1018a328fdca621819d74c6",
									},
									{
										"name": "kind",
										"value": "task",
									},
								],
								"resolver": "bundles",
							},
							"when": [{
								"input": "$(params.skip-checks)",
								"operator": "in",
								"values": ["false"],
							}],
						},
						{
							"name": "sast-shell-check",
							"params": [
								{
									"name": "image-digest",
									"value": "$(tasks.build-image-index.results.IMAGE_DIGEST)",
								},
								{
									"name": "image-url",
									"value": "$(tasks.build-image-index.results.IMAGE_URL)",
								},
								{
									"name": "SOURCE_ARTIFACT",
									"value": "$(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)",
								},
								{
									"name": "CACHI2_ARTIFACT",
									"value": "$(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)",
								},
							],
							"runAfter": ["build-image-index"],
							"taskRef": {
								"params": [
									{
										"name": "name",
										"value": "sast-shell-check-oci-ta",
									},
									{
										"name": "bundle",
										"value": "quay.io/konflux-ci/tekton-catalog/task-sast-shell-check-oci-ta:0.1@sha256:bf7bdde00b7212f730c1356672290af6f38d070da2c8a316987b5c32fd49e0b9",
									},
									{
										"name": "kind",
										"value": "task",
									},
								],
								"resolver": "bundles",
							},
							"when": [{
								"input": "$(params.skip-checks)",
								"operator": "in",
								"values": ["false"],
							}],
						},
						{
							"name": "sast-unicode-check",
							"params": [
								{
									"name": "image-digest",
									"value": "$(tasks.build-image-index.results.IMAGE_DIGEST)",
								},
								{
									"name": "image-url",
									"value": "$(tasks.build-image-index.results.IMAGE_URL)",
								},
								{
									"name": "SOURCE_ARTIFACT",
									"value": "$(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)",
								},
								{
									"name": "CACHI2_ARTIFACT",
									"value": "$(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)",
								},
							],
							"runAfter": ["build-image-index"],
							"taskRef": {
								"params": [
									{
										"name": "name",
										"value": "sast-unicode-check-oci-ta",
									},
									{
										"name": "bundle",
										"value": "quay.io/konflux-ci/tekton-catalog/task-sast-unicode-check-oci-ta:0.3@sha256:a2bde66f6b4164620298c7d709b8f08515409404000fa1dc2260d2508b135651",
									},
									{
										"name": "kind",
										"value": "task",
									},
								],
								"resolver": "bundles",
							},
							"when": [{
								"input": "$(params.skip-checks)",
								"operator": "in",
								"values": ["false"],
							}],
						},
						{
							"name": "apply-tags",
							"params": [
								{
									"name": "IMAGE_URL",
									"value": "$(tasks.build-image-index.results.IMAGE_URL)",
								},
								{
									"name": "IMAGE_DIGEST",
									"value": "$(tasks.build-image-index.results.IMAGE_DIGEST)",
								},
							],
							"runAfter": ["build-image-index"],
							"taskRef": {
								"params": [
									{
										"name": "name",
										"value": "apply-tags",
									},
									{
										"name": "bundle",
										"value": "quay.io/konflux-ci/tekton-catalog/task-apply-tags:0.2@sha256:f44be1bf0262471f2f503f5e19da5f0628dcaf968c86272a2ad6b4871e708448",
									},
									{
										"name": "kind",
										"value": "task",
									},
								],
								"resolver": "bundles",
							},
						},
						{
							"name": "push-dockerfile",
							"params": [
								{
									"name": "IMAGE",
									"value": "$(tasks.build-image-index.results.IMAGE_URL)",
								},
								{
									"name": "IMAGE_DIGEST",
									"value": "$(tasks.build-image-index.results.IMAGE_DIGEST)",
								},
								{
									"name": "DOCKERFILE",
									"value": "$(params.dockerfile)",
								},
								{
									"name": "CONTEXT",
									"value": "$(params.path-context)",
								},
								{
									"name": "SOURCE_ARTIFACT",
									"value": "$(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)",
								},
							],
							"runAfter": ["build-image-index"],
							"taskRef": {
								"params": [
									{
										"name": "name",
										"value": "push-dockerfile-oci-ta",
									},
									{
										"name": "bundle",
										"value": "quay.io/konflux-ci/tekton-catalog/task-push-dockerfile-oci-ta:0.1@sha256:2bc5b3afc5de56da0f06eac60b65e86f6b861b16a63f48579fc0bac7d657e14c",
									},
									{
										"name": "kind",
										"value": "task",
									},
								],
								"resolver": "bundles",
							},
						},
						{
							"name": "rpms-signature-scan",
							"params": [
								{
									"name": "image-url",
									"value": "$(tasks.build-image-index.results.IMAGE_URL)",
								},
								{
									"name": "image-digest",
									"value": "$(tasks.build-image-index.results.IMAGE_DIGEST)",
								},
							],
							"runAfter": ["build-image-index"],
							"taskRef": {
								"params": [
									{
										"name": "name",
										"value": "rpms-signature-scan",
									},
									{
										"name": "bundle",
										"value": "quay.io/konflux-ci/konflux-vanguard/task-rpms-signature-scan:0.2@sha256:06977232e67509e5540528ff6c3b081b23fc5bf3e40fb3e2d09a086d5c3243fc",
									},
									{
										"name": "kind",
										"value": "task",
									},
								],
								"resolver": "bundles",
							},
							"when": [{
								"input": "$(params.skip-checks)",
								"operator": "in",
								"values": ["false"],
							}],
						},
					],
					"workspaces": [
						{
							"name": "git-auth",
							"optional": true,
						},
						{
							"name": "netrc",
							"optional": true,
						},
					],
				},
				"taskRunTemplate": {"serviceAccountName": "build-pipeline-cli"},
				"timeouts": {"pipeline": "1h0m0s"},
				"workspaces": [{
					"name": "git-auth",
					"secret": {"secretName": "pac-gitauth-shmbmv"},
				}],
			}},
			"internalParameters": {"tekton-pipelines-feature-flags": {
				"awaitSidecarReadiness": true,
				"coschedule": "workspaces",
				"enableAPIFields": "beta",
				"enableProvenanceInStatus": true,
				"enforceNonfalsifiability": "none",
				"maxResultSize": 4096,
				"resultExtractionMethod": "termination-message",
				"runningInEnvWithInjectedSidecars": true,
				"verificationNoMatchPolicy": "ignore",
			}},
			"resolvedDependencies": [
				{
					"digest": {"sha256": "bbf313b09740fb39b3343bc69ee94b2a2c21d16a9304f9b7c111c305558fc346"},
					"name": "pipelineTask",
					"uri": "quay.io/konflux-ci/tekton-catalog/task-init",
				},
				{
					"digest": {"sha256": "4dd469452709b8a4ef0d279b8a13c4195150ba24875a869bd0058bca2aa719f2"},
					"uri": "oci://registry.access.redhat.com/ubi9/skopeo",
				},
				{
					"digest": {"sha256": "f21c34e50500edc84e4889d85fd71a80d79182b16c044adc7f5ecda021c6dfc7"},
					"name": "pipelineTask",
					"uri": "quay.io/konflux-ci/tekton-catalog/task-git-clone-oci-ta",
				},
				{
					"digest": {"sha256": "6d95e6001e28a59f64a51c35a1ca5d383f9fe3833c6d563650bbf83643edd8d9"},
					"uri": "oci://quay.io/konflux-ci/git-clone",
				},
				{
					"digest": {"sha256": "adf22f3ec90bfa3f7e2c832a7d52febd1ea31aa9fff6db21324c965d7d622327"},
					"uri": "oci://quay.io/konflux-ci/build-trusted-artifacts",
				},
				{
					"digest": {"sha256": "dc82a7270aace9b1c26f7e96f8ccab2752e53d32980c41a45e1733baad76cde6"},
					"name": "pipelineTask",
					"uri": "quay.io/konflux-ci/tekton-catalog/task-prefetch-dependencies-oci-ta",
				},
				{
					"digest": {"sha256": "7c5495d5fad59aaee12abc3cbbd2b283818ee1e814b00dbc7f25bf2d14fa4f0c"},
					"uri": "oci://registry.access.redhat.com/ubi9/ubi-minimal",
				},
				{
					"digest": {"sha256": "24c87766e0bd03b288e69034d629d3fbdda50cef95a661caae553cb20adf04f8"},
					"uri": "oci://quay.io/konflux-ci/yq",
				},
				{
					"digest": {"sha256": "edcbf837eb289da50a4d65f630a8bb1938ba8fa1e9ae617a224b6d349b2ae3f2"},
					"uri": "oci://quay.io/konflux-ci/hermeto",
				},
				{
					"digest": {"sha256": "38d08ea58511a67f8754dc025feebdec8ae342fb4e25bc67a3726ec84f7cb7d1"},
					"name": "pipelineTask",
					"uri": "quay.io/konflux-ci/tekton-catalog/task-buildah-oci-ta",
				},
				{
					"digest": {"sha256": "27400eaf836985bcc35182d62d727629f061538f61603c05b85d5d99bfa7da2d"},
					"uri": "oci://quay.io/konflux-ci/buildah-task",
				},
				{
					"digest": {"sha256": "dc0da6b4448428e625271b542cc029ab03de92f75ea50d6d63b1d088d20bbd28"},
					"uri": "oci://registry.access.redhat.com/rh-syft-tech-preview/syft-rhel9",
				},
				{
					"digest": {"sha256": "41e877cac3bda4ae5b8a59bbb8241e6f56dc18750476e6ce979264de161516dc"},
					"uri": "oci://quay.io/konflux-ci/mobster",
				},
				{
					"digest": {"sha256": "90ac97b811073cb99a23232c15a08082b586c702b85da6200cf54ef505e3c50c"},
					"uri": "oci://quay.io/konflux-ci/appstudio-utils",
				},
				{
					"digest": {"sha256": "79784d53749584bc5a8de32142ec4e2f01cdbf42c20d94e59280e0b927c8597d"},
					"name": "pipelineTask",
					"uri": "quay.io/konflux-ci/tekton-catalog/task-build-image-index",
				},
				{
					"digest": {"sha256": "1d07d16810c26713f3d875083924d93697900147364360587ccb5a63f2c31012"},
					"name": "pipelineTask",
					"uri": "quay.io/konflux-ci/tekton-catalog/task-deprecated-image-check",
				},
				{
					"digest": {"sha256": "e4f22a48ed1c029a3b43f81fb216b76fabb9fc5fba516f69c09553310e1bc170"},
					"uri": "oci://quay.io/konflux-ci/konflux-test",
				},
				{
					"digest": {"sha256": "a7cc183967f89c4ac100d04ab8f81e54733beee60a0528208107c9a22d3c43af"},
					"name": "pipelineTask",
					"uri": "quay.io/konflux-ci/tekton-catalog/task-clair-scan",
				},
				{
					"digest": {"sha256": "4a5423e125fc28db800421422d9933290dc4b62a22401d74cd3348c03107a5d9"},
					"uri": "oci://quay.io/konflux-ci/konflux-test",
				},
				{
					"digest": {"sha256": "022a5e23a44b074d9fca28670b3a679bd842cee62961794cc96b05e34a39ebbf"},
					"uri": "oci://quay.io/konflux-ci/clair-in-ci",
				},
				{
					"digest": {"sha256": "1beeecce012c99794568f74265c065839f9703d28306a8430b667f639343a98b"},
					"uri": "oci://quay.io/konflux-ci/oras",
				},
				{
					"digest": {"sha256": "7db70c6cf23f39b9aad8b75285df31ed2c1213d87842cd4502ffc268808c96c6"},
					"name": "pipelineTask",
					"uri": "quay.io/konflux-ci/tekton-catalog/task-ecosystem-cert-preflight-checks",
				},
				{
					"digest": {"sha256": "4542f5a2a046ca36653749a8985e46744a5d2d36ee10ca14409be718ce15129e"},
					"uri": "oci://quay.io/konflux-ci/oras",
				},
				{
					"digest": {"sha256": "a7cae9e96663e277a3904d0c78630508ddb6cc8eebaa912a840bd20f68dcaad1"},
					"uri": "oci://quay.io/redhat-appstudio/konflux-test",
				},
				{
					"digest": {"sha256": "57f74e3d1ad72bfd11cf888eae99f8cad4d75c25515413a7c30ad9963aed2741"},
					"uri": "oci://quay.io/opdev/preflight",
				},
				{
					"digest": {"sha256": "181d63c126e3119a9d57b8feed4eb66a875b5208c3e90724c22758e65dca8733"},
					"name": "pipelineTask",
					"uri": "quay.io/konflux-ci/tekton-catalog/task-sast-snyk-check-oci-ta",
				},
				{
					"digest": {"sha256": "4689f88dd253bd1feebf57f1a76a5a751880f739000719cd662bbdc76990a7fd"},
					"uri": "oci://quay.io/konflux-ci/build-trusted-artifacts",
				},
				{
					"digest": {"sha256": "b0bd59748cda4a7abf311e4f448e6c1d00c6b6d8c0ecc1c2eb33e08dc0e0b802"},
					"name": "pipelineTask",
					"uri": "quay.io/konflux-ci/tekton-catalog/task-clamav-scan",
				},
				{
					"digest": {"sha256": "7ada6c0c25e82268700237fb92e1ea838e00e9f3c5f4b42fd14c4d80e34a9450"},
					"uri": "oci://quay.io/konflux-ci/clamav-db",
				},
				{
					"digest": {"sha256": "8d756a91aae1fa5186efafee056446bb5e77228cf5ad9a7ae0e3f8d727da50cd"},
					"uri": "oci://quay.io/konflux-ci/oras",
				},
				{
					"digest": {"sha256": "db2b267dc15e4ed17f704ee91b8e9b38068e1a35b1018a328fdca621819d74c6"},
					"name": "pipelineTask",
					"uri": "quay.io/konflux-ci/tekton-catalog/task-coverity-availability-check",
				},
				{
					"digest": {"sha256": "bf7bdde00b7212f730c1356672290af6f38d070da2c8a316987b5c32fd49e0b9"},
					"name": "pipelineTask",
					"uri": "quay.io/konflux-ci/tekton-catalog/task-sast-shell-check-oci-ta",
				},
				{
					"digest": {"sha256": "7e04a34cc9adb5fa0bfe5070d1a60321205f5e6f0cd3fb2e8a33a5ec8508fd29"},
					"uri": "oci://quay.io/konflux-ci/konflux-test",
				},
				{
					"digest": {"sha256": "a2bde66f6b4164620298c7d709b8f08515409404000fa1dc2260d2508b135651"},
					"name": "pipelineTask",
					"uri": "quay.io/konflux-ci/tekton-catalog/task-sast-unicode-check-oci-ta",
				},
				{
					"digest": {"sha256": "f44be1bf0262471f2f503f5e19da5f0628dcaf968c86272a2ad6b4871e708448"},
					"name": "pipelineTask",
					"uri": "quay.io/konflux-ci/tekton-catalog/task-apply-tags",
				},
				{
					"digest": {"sha256": "2bc5b3afc5de56da0f06eac60b65e86f6b861b16a63f48579fc0bac7d657e14c"},
					"name": "pipelineTask",
					"uri": "quay.io/konflux-ci/tekton-catalog/task-push-dockerfile-oci-ta",
				},
				{
					"digest": {"sha256": "06977232e67509e5540528ff6c3b081b23fc5bf3e40fb3e2d09a086d5c3243fc"},
					"name": "pipelineTask",
					"uri": "quay.io/konflux-ci/konflux-vanguard/task-rpms-signature-scan",
				},
				{
					"digest": {"sha256": "21ea4a98b1784a2b8103338c46b92a5f53a47f981ba2207d8ed534b0bb0e95f0"},
					"uri": "oci://quay.io/konflux-ci/tools",
				},
				{
					"digest": {"sha256": "89cdc9d251e15d07018548137b4034669df8e9e2b171a188c8b8201d3638cb17"},
					"uri": "oci://quay.io/konflux-ci/konflux-test",
				},
				{
					"digest": {"sha1": "82126ebeeb0d80883d5d85f4f48066821464e3d8"},
					"name": "inputs/result",
					"uri": "git+https://github.com/st3penta/cli.git",
				},
			],
		},
		"runDetails": {
			"builder": {"id": "https://tekton.dev/chains/v2"},
			"byproducts": [
				{
					"content": "Imh0dHBzOi8vZ2l0aHViLmNvbS9zdDNwZW50YS9jbGki",
					"mediaType": "application/json",
					"name": "pipelineRunResults/CHAINS-GIT_URL",
				},
				{
					"content": "IjgyMTI2ZWJlZWIwZDgwODgzZDVkODVmNGY0ODA2NjgyMTQ2NGUzZDgi",
					"mediaType": "application/json",
					"name": "pipelineRunResults/CHAINS-GIT_COMMIT",
				},
				{
					"content": "InRydWUi",
					"mediaType": "application/json",
					"name": "taskRunResults/build",
				},
				{
					"content": "IjgyMTI2ZWJlZWIwZDgwODgzZDVkODVmNGY0ODA2NjgyMTQ2NGUzZDgi",
					"mediaType": "application/json",
					"name": "taskRunResults/CHAINS-GIT_COMMIT",
				},
				{
					"content": "Imh0dHBzOi8vZ2l0aHViLmNvbS9zdDNwZW50YS9jbGki",
					"mediaType": "application/json",
					"name": "taskRunResults/CHAINS-GIT_URL",
				},
				{
					"content": "IjgyMTI2ZWJlZWIwZDgwODgzZDVkODVmNGY0ODA2NjgyMTQ2NGUzZDgi",
					"mediaType": "application/json",
					"name": "taskRunResults/commit",
				},
				{
					"content": "IjE3NTk4MzA3ODEi",
					"mediaType": "application/json",
					"name": "taskRunResults/commit-timestamp",
				},
				{
					"content": "IjgyMTI2ZWIi",
					"mediaType": "application/json",
					"name": "taskRunResults/short-commit",
				},
				{
					"content": "Imh0dHBzOi8vZ2l0aHViLmNvbS9zdDNwZW50YS9jbGki",
					"mediaType": "application/json",
					"name": "taskRunResults/url",
				},
				{
					"content": "Im9jaTpxdWF5LmlvL3N0M3BlbnRhLWtvbmZsdXgtdGVzdC1yZWdpc3RyeS91c2VyLW5zMi9jbGlAc2hhMjU2OjgxMzBjYTczY2Q3NWFlNzY4MDJiNmNhZDhmYTU2YmYzOTdjYzM5MGUwYjEwZGYyNzlkYTA0ZWExMTNhYTlkMjgi",
					"mediaType": "application/json",
					"name": "taskRunResults/SOURCE_ARTIFACT",
				},
				{
					"content": "IiI=",
					"mediaType": "application/json",
					"name": "taskRunResults/CACHI2_ARTIFACT",
				},
				{
					"content": "Im9jaTpxdWF5LmlvL3N0M3BlbnRhLWtvbmZsdXgtdGVzdC1yZWdpc3RyeS91c2VyLW5zMi9jbGlAc2hhMjU2OjgxMzBjYTczY2Q3NWFlNzY4MDJiNmNhZDhmYTU2YmYzOTdjYzM5MGUwYjEwZGYyNzlkYTA0ZWExMTNhYTlkMjgi",
					"mediaType": "application/json",
					"name": "taskRunResults/SOURCE_ARTIFACT",
				},
				{
					"content": "InF1YXkuaW8vc3QzcGVudGEta29uZmx1eC10ZXN0LXJlZ2lzdHJ5L3VzZXItbnMyL2NsaTo4MjEyNmViZWViMGQ4MDg4M2Q1ZDg1ZjRmNDgwNjY4MjE0NjRlM2Q4QHNoYTI1NjplYzlmZjQ1NTlhZTA5OWIwN2MyNGM3MTI1N2JkMjU4NTliMGZiZGQ0NDE0YTEyY2Q0NjFiYTI2MWJhMDE4ZTMxIg==",
					"mediaType": "application/json",
					"name": "taskRunResults/IMAGE_REF",
				},
				{
					"content": "InF1YXkuaW8vc3QzcGVudGEta29uZmx1eC10ZXN0LXJlZ2lzdHJ5L3VzZXItbnMyL2NsaUBzaGEyNTY6MjgzZTU5ZTFlMGQ1NWJmNWRkYmFjMmNmNDNhYWQyMzRkYWE5MTgyY2E1YmEyNTIyZTYzMWVmYTMzY2Y3MTFhZSI=",
					"mediaType": "application/json",
					"name": "taskRunResults/SBOM_BLOB_URL",
				},
				{
					"content": "IntcImltYWdlXCI6IHtcInB1bGxzcGVjXCI6IFwicXVheS5pby9zdDNwZW50YS1rb25mbHV4LXRlc3QtcmVnaXN0cnkvdXNlci1uczIvY2xpOjgyMTI2ZWJlZWIwZDgwODgzZDVkODVmNGY0ODA2NjgyMTQ2NGUzZDhcIiwgXCJkaWdlc3RzXCI6IFtcInNoYTI1NjplYzlmZjQ1NTlhZTA5OWIwN2MyNGM3MTI1N2JkMjU4NTliMGZiZGQ0NDE0YTEyY2Q0NjFiYTI2MWJhMDE4ZTMxXCJdfX1cbiI=",
					"mediaType": "application/json",
					"name": "taskRunResults/IMAGES_PROCESSED",
				},
				{
					"content": "IntcInJlc3VsdFwiOlwiV0FSTklOR1wiLFwidGltZXN0YW1wXCI6XCIyMDI1LTEwLTA3VDEwOjAwOjMxKzAwOjAwXCIsXCJub3RlXCI6XCJUYXNrIGRlcHJlY2F0ZWQtaW1hZ2UtY2hlY2sgY29tcGxldGVkOiBDaGVjayByZXN1bHQgZm9yIHRhc2sgcmVzdWx0LlwiLFwibmFtZXNwYWNlXCI6XCJyZXF1aXJlZF9jaGVja3NcIixcInN1Y2Nlc3Nlc1wiOjEsXCJmYWlsdXJlc1wiOjAsXCJ3YXJuaW5nc1wiOjF9XG4i",
					"mediaType": "application/json",
					"name": "taskRunResults/TEST_OUTPUT",
				},
				{
					"content": "IntcImltYWdlXCI6IHtcInB1bGxzcGVjXCI6IFwicXVheS5pby9zdDNwZW50YS1rb25mbHV4LXRlc3QtcmVnaXN0cnkvdXNlci1uczIvY2xpOjgyMTI2ZWJlZWIwZDgwODgzZDVkODVmNGY0ODA2NjgyMTQ2NGUzZDhcIiwgXCJkaWdlc3RzXCI6IFtcInNoYTI1NjplYzlmZjQ1NTlhZTA5OWIwN2MyNGM3MTI1N2JkMjU4NTliMGZiZGQ0NDE0YTEyY2Q0NjFiYTI2MWJhMDE4ZTMxXCJdfX1cbiI=",
					"mediaType": "application/json",
					"name": "taskRunResults/IMAGES_PROCESSED",
				},
				{
					"content": "IntcInNoYTI1NjplYzlmZjQ1NTlhZTA5OWIwN2MyNGM3MTI1N2JkMjU4NTliMGZiZGQ0NDE0YTEyY2Q0NjFiYTI2MWJhMDE4ZTMxXCI6XCJzaGEyNTY6NDM1NzI3MDMzZDcyY2Q5ZmM5NDY2NGI0Zjk0ZWQyMDM1YjZmOWQyOTcxNTA4MTQzYzNmODEzMjJhOTllOTIxYlwifVxuIg==",
					"mediaType": "application/json",
					"name": "taskRunResults/REPORTS",
				},
				{
					"content": "IntcInZ1bG5lcmFiaWxpdGllc1wiOntcImNyaXRpY2FsXCI6MCxcImhpZ2hcIjowLFwibWVkaXVtXCI6MCxcImxvd1wiOjAsXCJ1bmtub3duXCI6MH0sXCJ1bnBhdGNoZWRfdnVsbmVyYWJpbGl0aWVzXCI6e1wiY3JpdGljYWxcIjowLFwiaGlnaFwiOjAsXCJtZWRpdW1cIjoxMSxcImxvd1wiOjMzLFwidW5rbm93blwiOjl9fVxuIg==",
					"mediaType": "application/json",
					"name": "taskRunResults/SCAN_OUTPUT",
				},
				{
					"content": "IntcInJlc3VsdFwiOlwiU1VDQ0VTU1wiLFwidGltZXN0YW1wXCI6XCIyMDI1LTEwLTA3VDEwOjAyOjAxKzAwOjAwXCIsXCJub3RlXCI6XCJUYXNrIGNsYWlyLXNjYW4gY29tcGxldGVkOiBSZWZlciB0byBUZWt0b24gdGFzayByZXN1bHQgU0NBTl9PVVRQVVQgZm9yIHZ1bG5lcmFiaWxpdGllcyBzY2FubmVkIGJ5IENsYWlyLlwiLFwibmFtZXNwYWNlXCI6XCJkZWZhdWx0XCIsXCJzdWNjZXNzZXNcIjowLFwiZmFpbHVyZXNcIjowLFwid2FybmluZ3NcIjowfVxuIg==",
					"mediaType": "application/json",
					"name": "taskRunResults/TEST_OUTPUT",
				},
				{
					"content": "ImFwcGxpY2F0aW9uIg==",
					"mediaType": "application/json",
					"name": "taskRunResults/ARTIFACT_TYPE",
				},
				{
					"content": "ImludHJvc3BlY3Rpb24i",
					"mediaType": "application/json",
					"name": "taskRunResults/ARTIFACT_TYPE_SET_BY",
				},
				{
					"content": "IntcImltYWdlXCI6IHtcInB1bGxzcGVjXCI6IFwicXVheS5pby9zdDNwZW50YS1rb25mbHV4LXRlc3QtcmVnaXN0cnkvdXNlci1uczIvY2xpOjgyMTI2ZWJlZWIwZDgwODgzZDVkODVmNGY0ODA2NjgyMTQ2NGUzZDhcIiwgXCJkaWdlc3RzXCI6IFtcInNoYTI1NjplYzlmZjQ1NTlhZTA5OWIwN2MyNGM3MTI1N2JkMjU4NTliMGZiZGQ0NDE0YTEyY2Q0NjFiYTI2MWJhMDE4ZTMxXCJdfX0i",
					"mediaType": "application/json",
					"name": "taskRunResults/IMAGES_PROCESSED",
				},
				{
					"content": "IntcInJlc3VsdFwiOlwiU1VDQ0VTU1wiLFwidGltZXN0YW1wXCI6XCIxNzU5ODMxMzI4XCIsXCJub3RlXCI6XCJUYXNrIHByZWZsaWdodCBpcyBhIFNVQ0NFU1M6IFJlZmVyIHRvIFRla3RvbiB0YXNrIGxvZ3MgZm9yIG1vcmUgaW5mb3JtYXRpb25cIixcInN1Y2Nlc3Nlc1wiOjgsXCJmYWlsdXJlc1wiOjAsXCJ3YXJuaW5nc1wiOjB9Ig==",
					"mediaType": "application/json",
					"name": "taskRunResults/TEST_OUTPUT",
				},
				{
					"content": "ImFwcGxpY2F0aW9uIg==",
					"mediaType": "application/json",
					"name": "stepResults/artifact-type",
				},
				{
					"content": "ImludHJvc3BlY3Rpb24i",
					"mediaType": "application/json",
					"name": "stepResults/artifact-type-set-by",
				},
				{
					"content": "Ii9hdXRoL2F1dGguanNvbiI=",
					"mediaType": "application/json",
					"name": "stepResults/auth-json-path",
				},
				{
					"content": "IntcImltYWdlXCI6IHtcInB1bGxzcGVjXCI6IFwicXVheS5pby9zdDNwZW50YS1rb25mbHV4LXRlc3QtcmVnaXN0cnkvdXNlci1uczIvY2xpOjgyMTI2ZWJlZWIwZDgwODgzZDVkODVmNGY0ODA2NjgyMTQ2NGUzZDhcIiwgXCJkaWdlc3RzXCI6IFtcInNoYTI1NjplYzlmZjQ1NTlhZTA5OWIwN2MyNGM3MTI1N2JkMjU4NTliMGZiZGQ0NDE0YTEyY2Q0NjFiYTI2MWJhMDE4ZTMxXCJdfX0i",
					"mediaType": "application/json",
					"name": "stepResults/images-processed",
				},
				{
					"content": "IntcInJlc3VsdFwiOlwiU1VDQ0VTU1wiLFwidGltZXN0YW1wXCI6XCIxNzU5ODMxMzI4XCIsXCJub3RlXCI6XCJUYXNrIHByZWZsaWdodCBpcyBhIFNVQ0NFU1M6IFJlZmVyIHRvIFRla3RvbiB0YXNrIGxvZ3MgZm9yIG1vcmUgaW5mb3JtYXRpb25cIixcInN1Y2Nlc3Nlc1wiOjgsXCJmYWlsdXJlc1wiOjAsXCJ3YXJuaW5nc1wiOjB9Ig==",
					"mediaType": "application/json",
					"name": "stepResults/test-output",
				},
				{
					"content": "IntcInJlc3VsdFwiOlwiU1VDQ0VTU1wiLFwidGltZXN0YW1wXCI6XCIxNzU5ODMxMzI4XCIsXCJub3RlXCI6XCJUYXNrIHByZWZsaWdodCBpcyBhIFNVQ0NFU1M6IFJlZmVyIHRvIFRla3RvbiB0YXNrIGxvZ3MgZm9yIG1vcmUgaW5mb3JtYXRpb25cIixcInN1Y2Nlc3Nlc1wiOjgsXCJmYWlsdXJlc1wiOjAsXCJ3YXJuaW5nc1wiOjB9Ig==",
					"mediaType": "application/json",
					"name": "stepResults/test-output",
				},
				{
					"content": "IntcInJlc3VsdFwiOlwiU0tJUFBFRFwiLFwidGltZXN0YW1wXCI6XCIyMDI1LTEwLTA3VDEwOjAwOjI4KzAwOjAwXCIsXCJub3RlXCI6XCJUYXNrIHNhc3Qtc255ay1jaGVjay1vY2ktdGEgc2tpcHBlZDogSWYgeW91IHdpc2ggdG8gdXNlIHRoZSBTbnlrIGNvZGUgU0FTVCB0YXNrLCBwbGVhc2UgY3JlYXRlIGEgc2VjcmV0IG5hbWUgc255ay1zZWNyZXQgd2l0aCB0aGUga2V5ICdzbnlrX3Rva2VuJyBjb250YWluaW5nIHRoZSBTbnlrIHRva2VuIGJ5IGZvbGxvd2luZyB0aGUgc3RlcHMgZ2l2ZW4gW2hlcmVdKGh0dHBzOi8va29uZmx1eC1jaS5kZXYvZG9jcy90ZXN0aW5nL2J1aWxkL3NueWsvKVwiLFwibmFtZXNwYWNlXCI6XCJkZWZhdWx0XCIsXCJzdWNjZXNzZXNcIjowLFwiZmFpbHVyZXNcIjowLFwid2FybmluZ3NcIjowfVxuIg==",
					"mediaType": "application/json",
					"name": "taskRunResults/TEST_OUTPUT",
				},
				{
					"content": "IntcImltYWdlXCI6IHtcInB1bGxzcGVjXCI6IFwicXVheS5pby9zdDNwZW50YS1rb25mbHV4LXRlc3QtcmVnaXN0cnkvdXNlci1uczIvY2xpOjgyMTI2ZWJlZWIwZDgwODgzZDVkODVmNGY0ODA2NjgyMTQ2NGUzZDhcIiwgXCJkaWdlc3RzXCI6IFtcInNoYTI1NjplYzlmZjQ1NTlhZTA5OWIwN2MyNGM3MTI1N2JkMjU4NTliMGZiZGQ0NDE0YTEyY2Q0NjFiYTI2MWJhMDE4ZTMxXCJdfX1cbiI=",
					"mediaType": "application/json",
					"name": "taskRunResults/IMAGES_PROCESSED",
				},
				{
					"content": "IntcInRpbWVzdGFtcFwiOlwiMTc1OTgzMTMzNFwiLFwibmFtZXNwYWNlXCI6XCJyZXF1aXJlZF9jaGVja3NcIixcInN1Y2Nlc3Nlc1wiOjIsXCJmYWlsdXJlc1wiOjAsXCJ3YXJuaW5nc1wiOjAsXCJyZXN1bHRcIjpcIlNVQ0NFU1NcIixcIm5vdGVcIjpcIkFsbCBjaGVja3MgcGFzc2VkIHN1Y2Nlc3NmdWxseVwifVxuIg==",
					"mediaType": "application/json",
					"name": "taskRunResults/TEST_OUTPUT",
				},
				{
					"content": "ImZhaWxlZCI=",
					"mediaType": "application/json",
					"name": "taskRunResults/STATUS",
				},
				{
					"content": "IntcInJlc3VsdFwiOlwiRkFJTFVSRVwiLFwidGltZXN0YW1wXCI6XCIyMDI1LTEwLTA3VDEwOjAwOjIzKzAwOjAwXCIsXCJub3RlXCI6XCJUYXNrIGNvdmVyaXR5LWF2YWlsYWJpbGl0eS1jaGVjayBmYWlsZWQ6IE5vIGxpY2Vuc2UgZmlsZSBmb3IgQ292ZXJpdHkgd2FzIGRldGVjdGVkLiBQbGVhc2UsIGNyZWF0ZSBhIHNlY3JldCBjYWxsZWQgJ2Nvdi1saWNlbnNlJyB3aXRoIGEga2V5IGNhbGxlZCAnY292LWxpY2Vuc2UnIGFuZCB0aGUgdmFsdWUgY29udGFpbmluZyB0aGUgQ292ZXJpdHkgbGljZW5zZVwiLFwibmFtZXNwYWNlXCI6XCJkZWZhdWx0XCIsXCJzdWNjZXNzZXNcIjowLFwiZmFpbHVyZXNcIjoxLFwid2FybmluZ3NcIjowfVxuIg==",
					"mediaType": "application/json",
					"name": "taskRunResults/TEST_OUTPUT",
				},
				{
					"content": "IntcInJlc3VsdFwiOlwiU1VDQ0VTU1wiLFwidGltZXN0YW1wXCI6XCIyMDI1LTEwLTA3VDEwOjAwOjMyKzAwOjAwXCIsXCJub3RlXCI6XCJUYXNrIHNhc3Qtc2hlbGwtY2hlY2stb2NpLXRhIGNvbXBsZXRlZCBzdWNjZXNzZnVsbHkuXCIsXCJuYW1lc3BhY2VcIjpcImRlZmF1bHRcIixcInN1Y2Nlc3Nlc1wiOjAsXCJmYWlsdXJlc1wiOjAsXCJ3YXJuaW5nc1wiOjB9XG4i",
					"mediaType": "application/json",
					"name": "taskRunResults/TEST_OUTPUT",
				},
				{
					"content": "IntcInJlc3VsdFwiOlwiU1VDQ0VTU1wiLFwidGltZXN0YW1wXCI6XCIyMDI1LTEwLTA3VDEwOjAwOjMzKzAwOjAwXCIsXCJub3RlXCI6XCJUYXNrIHNhc3QtdW5pY29kZS1jaGVjay1vY2ktdGEgc3VjY2VzczogTm8gZmluZGluZyB3YXMgZGV0ZWN0ZWRcIixcIm5hbWVzcGFjZVwiOlwiZGVmYXVsdFwiLFwic3VjY2Vzc2VzXCI6MCxcImZhaWx1cmVzXCI6MCxcIndhcm5pbmdzXCI6MH1cbiI=",
					"mediaType": "application/json",
					"name": "taskRunResults/TEST_OUTPUT",
				},
				{
					"content": "InF1YXkuaW8vc3QzcGVudGEta29uZmx1eC10ZXN0LXJlZ2lzdHJ5L3VzZXItbnMyL2NsaUBzaGEyNTY6ZDgwYjI2YTE2MmU3NTllMTkxNDEyM2M3NWRiMDM0MzUwNTRhYzQyZTg0NDhjMDAwNWEyMzJiMTMyN2IxZTg3OCI=",
					"mediaType": "application/json",
					"name": "taskRunResults/IMAGE_REF",
				},
				{
					"content": "IntcImltYWdlXCI6IHtcInB1bGxzcGVjXCI6IFwicXVheS5pby9zdDNwZW50YS1rb25mbHV4LXRlc3QtcmVnaXN0cnkvdXNlci1uczIvY2xpOjgyMTI2ZWJlZWIwZDgwODgzZDVkODVmNGY0ODA2NjgyMTQ2NGUzZDhcIiwgXCJkaWdlc3RzXCI6IFtcInNoYTI1NjplYzlmZjQ1NTlhZTA5OWIwN2MyNGM3MTI1N2JkMjU4NTliMGZiZGQ0NDE0YTEyY2Q0NjFiYTI2MWJhMDE4ZTMxXCJdfX1cbiI=",
					"mediaType": "application/json",
					"name": "taskRunResults/IMAGES_PROCESSED",
				},
				{
					"content": "IntcImtleXNcIjoge1wiMTk5ZTJmOTFmZDQzMWQ1MVwiOiAxMDksIFwidW5zaWduZWRcIjogMH19XG4i",
					"mediaType": "application/json",
					"name": "taskRunResults/RPMS_DATA",
				},
				{
					"content": "IntcInJlc3VsdFwiOlwiU1VDQ0VTU1wiLFwidGltZXN0YW1wXCI6XCIyMDI1LTEwLTA3VDEwOjAxOjU0KzAwOjAwXCIsXCJub3RlXCI6XCJUYXNrIHJwbXMtc2lnbmF0dXJlLXNjYW4gY29tcGxldGVkIHN1Y2Nlc3NmdWxseVwiLFwibmFtZXNwYWNlXCI6XCJkZWZhdWx0XCIsXCJzdWNjZXNzZXNcIjowLFwiZmFpbHVyZXNcIjowLFwid2FybmluZ3NcIjowfVxuIg==",
					"mediaType": "application/json",
					"name": "taskRunResults/TEST_OUTPUT",
				},
			],
			"metadata": {
				"finishedOn": "2025-10-07T10:02:19Z",
				"invocationId": "50b012fb-e8e1-462f-bacf-7e672c5fb491",
				"startedOn": "2025-10-07T09:53:09Z",
			},
		},
	},
}
